// <auto-generated />
using System;
using Desafio.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio.Infrastructure.Persistencia.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Desafio.Domain.Beneficiarios.Beneficiario", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Cpf")
                    .IsRequired()
                    .HasMaxLength(11)
                    .HasColumnType("character varying(11)");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateOnly>("DataNascimento")
                    .HasColumnType("date");

                b.Property<DateTime?>("ExcluidoEm")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NomeCompleto")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<Guid>("PlanoId")
                    .HasColumnType("uuid");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.HasKey("Id");

                b.HasIndex("Cpf")
                    .IsUnique();

                b.HasIndex("PlanoId");

                b.ToTable("Beneficiarios", (string)null);
            });

        modelBuilder.Entity("Desafio.Domain.Planos.Plano", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CodigoRegistroAns")
                    .IsRequired()
                    .HasMaxLength(6)
                    .HasColumnType("character varying(6)");

                b.Property<DateTime?>("ExcluidoEm")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(60)
                    .HasColumnType("character varying(60)");

                b.HasKey("Id");

                b.HasIndex("CodigoRegistroAns")
                    .IsUnique();

                b.HasIndex("Nome")
                    .IsUnique();

                b.ToTable("Planos", (string)null);
            });

        modelBuilder.Entity("Desafio.Domain.Beneficiarios.Beneficiario", b =>
            {
                b.HasOne("Desafio.Domain.Planos.Plano", "Plano")
                    .WithMany()
                    .HasForeignKey("PlanoId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Plano");
            });
#pragma warning restore 612, 618
    }
}
